### ISSUE TITLE
请问如何初始化绑定已有marker

### ISSUE THREAD

**Issue by zhdwwf** [FRED5DON/vue-ui-picture-bd-marker#1]
请问已经保存有marker数据的情况下，如何绑定到组件中显示，文档中没有找到对应的绑定方法

**Comment by zhdwwf** [comment]
在源码中找到了，使用renderData，建议能在文档中加一下说明

**Comment by sunshengfei** [comment]
请查看文档 https://vmarker.sagocloud.com/doc/ 谢谢反馈
