### ISSUE TITLE
图像放大、拖拽功能是否有较好的解决方案

### ISSUE THREAD

**Issue by lihongyang166** [FRED5DON/vue-ui-picture-bd-marker#11]
图像标注过程中，需要对图像进行放大、拖拽等操作，请问该如何实现？

**Comment by sunshengfei** [comment]
类似地图那样的吗，目前的库不支持map模式

因为初始化就根据bounding获取到边界进行渲染的，可能需要你自己改改

2020年8月19日 00:29，lihongyang166 <notifications@github.com<mailto:notifications@github.com>> 写道：



图像标注过程中，需要对图像进行放大、拖拽等操作，请问该如何实现？
