### ISSUE TITLE
在IE上的兼容性。IE上不能进行框选怎么解决

### ISSUE THREAD

**Issue by madfour** [FRED5DON/vue-ui-picture-bd-marker#12]

**Comment by sunshengfei** [comment]
可以把控制台报错截图给我吗 ,issues 可以直接粘贴图
或者 gsiner@live.com

**Comment by madfour** [comment]
1、https://vmarker.sagocloud.com/about/ 在IE11上打开时，会发现所有带标框功能的图是都不显示的；
2、可以通过DOM管理器修改样式，把图片等显示出来。但当用鼠标进行标框时是没有反应的，控制台也不抛出错误；
3、切换目录也会报出很多“对象不支持‘****’属性或方法”；

**Comment by sunshengfei** [comment]
文档网站在IE上可能还无法适配，但是新版本应该可以用了
