### ISSUE TITLE
onUpdated返回的uniqueKey为undefined

### ISSUE THREAD

**Issue by xiaomosimon** [FRED5DON/vue-ui-picture-bd-marker#14]
![错误2](https://user-images.githubusercontent.com/38958639/103882505-dc2d0380-5116-11eb-92e2-e9395daeefa6.jpg)

**Comment by sunshengfei** [comment]
修复了 1.4.0

**Comment by xiaomosimon** [comment]
谢谢


| |
healer
|
|
lx1996082566@126.com
|
签名由网易邮箱大师定制


在2021年01月7日 23:32，sunshengfei<notifications@github.com> 写道：

Closed #14.
