### ISSUE TITLE
7点不成熟的建议

### ISSUE THREAD

**Issue by xiyuan27** [FRED5DON/vue-ui-picture-bd-marker#2]
试用了一下，个人有下面7个建议
1. 删除标注和修改标注时，预留的事件钩子没有分开，而且事件参数好像没有返回到底删除了哪个，修改了哪个，感觉好像不是很方便。 建议事件处理函数里面，可以明确获取到当前添加了，删掉了，修改了哪个。

2.当标注框太小的时候，整个标注框都被关闭按钮(那个x按钮）给罩住了，双击事件触发不了，
   建议：通过参数控制(x)关闭按钮和右键菜单>删除菜单项，两种方式删除

3.建议标注数据的数据结构，还可以挂自定义的一个对象进去，因为标注不单单是坐标数据和label数据，实际场景很可能还要标注其他很多内容。也就是标注数据最好可以附加一个自定义的数据结构，存放其他信息。

4.双击和鼠标右键菜单，最好有口子，可以添加自定义的弹出窗口，编辑一些附加数据

5.最好能像百度的单据识别模板标注那样，提供字段，表格等多种标注（参考https://ai.baidu.com/iocr）

6. 现在点击(x)按钮，好像删不掉，刷新一下又出来了。（这个可能是我版本问题）

7.除了nodejs的npm方式安装，最好可以给我们这种后台开发友好的使用方式，
         比如：一个vue文件，或html文件，下载某几个js，然后手工添加js的引入路径，就可以快速体验起来，而不是npm install  和build， 这个太慢了（即便是cnpm)

8. 标注数据给后台持久化的口子，要是能更加方便一点就好了，不过这个目前也OK

**Comment by sunshengfei** [comment]
非常感谢你的建议，我们会酌情采纳的，届时请关注新版本。Thanks♪(･ω･)ﾉ

**Comment by sunshengfei** [comment]
好的，关于第6点，请重新安装 
```
npm uninstall vue-picture-bd-marker
npm install vue-picture-bd-marker
```
第7点，可以访问 `https://www.unpkg.com/` 生成CDN，
`https://www.unpkg.com/vue-picture-bd-marker@1.3.0/dist/index.js`
当然,后面会提供离线js下载和cdn连接
