### ISSUE TITLE
关于readOnly的bug

### ISSUE THREAD

**Issue by kvtiann** [FRED5DON/vue-ui-picture-bd-marker#22]
如果在renderData前设置 readOnly 设置true  能够能正常使得不能图片不能编辑 且加载的标注框不能移动。 但是再将readOnly  设置为false时，此时可编辑，但原来的标注框不能拖动，只有新画一个标注框，原来的那些标注框才能拖动。
如果在 renderData后设置readOnly 设置true，此时 不能编辑，但是标注框能够拖动

**Comment by sunshengfei** [comment]
3q，已记录，请提供版本号，是最新的吗

2021年6月16日 17:31，Daniel Wang ***@***.******@***.***>> 写道：



如果在renderData前设置 readOnly 设置true 能够能正常使得不能图片不能编辑 且加载的标注框不能移动。 但是再将readOnly 设置为false时，此时可编辑，但原来的标注框不能拖动，只有新画一个标注框，原来的那些标注框才能拖动。
如果在 renderData后设置readOnly 设置true，此时 不能编辑，但是标注框能够拖动

**Comment by kvtiann** [comment]
嗯     ^1.4.1-beta02

**Comment by sunshengfei** [comment]
@kvtiann  更新了，1.4.2
