### ISSUE TITLE
关于1.3.0版本的clearData失效，无法清空标注信息

### ISSUE THREAD

**Issue by huicrh** [FRED5DON/vue-ui-picture-bd-marker#3]
.getMarker().clearData()这个方法无法清空界面的标注信息

**Comment by sunshengfei** [comment]
已经有人反馈了，站长正在处理，谢谢。

2019年11月1日 10:47，huicrh <notifications@github.com<mailto:notifications@github.com>> 写道：


.getMarker().clearData()这个方法无法清空界面的标注信息

**Comment by sunshengfei** [comment]
@huicrh  已经发布了，你重新install 一下
```
npm uninstall vue-picture-bd-marker
 
npm install vue-picture-bd-marker
```

**Comment by huicrh** [comment]
你好。重新Install了clearData方法还是不能使用。具体表现为data值虽然被清空，但是界面的标注框还存在。
vue-picture-bd-marker版本为v1.3.0。ui-picture-bd-marker版本为2.0.1

**Comment by sunshengfei** [comment]
好的，已记录，尽快排查。

2019年11月1日 14:28，huicrh <notifications@github.com<mailto:notifications@github.com>> 写道：


你好。重新Install了clearData方法还是不能使用。具体表现为data值虽然被清空，但是界面的标注框还存在。
vue-picture-bd-marker版本为v1.3.0。ui-picture-bd-marker版本为2.0.1

**Comment by sunshengfei** [comment]
@huicrh  
我测试了线上的的1.3.0确实有问题，但是我本地的pkg包是ok的，可能是缓存吧。
只改了版本号，已经重新发布了你看一下。现在是1.3.1
