### ISSUE TITLE
1.33版本vmarker:onImageLoad事件没有触发

### ISSUE THREAD

**Issue by WindBise** [FRED5DON/vue-ui-picture-bd-marker#5]
需求时想要在图片加载完之后打印出原图的长和宽，但是事件好像没有触发
代码形如
<ui-marker
                ref="aiPanel-editor"
                class="ai-observer"
                :uniqueKey="uuid"
                :imgUrl="image"
                @vmarker:onImageLoad="onImageLoad"
              ></ui-marker>

**Comment by sunshengfei** [comment]
image是base64吧，url的没问题，我测过了
最近会发新版。
