### ISSUE TITLE
大量数据，显示不完整，需要x-6,y-12才能显示出来所有的数据

### ISSUE THREAD

**Issue by wzl26999821** [FRED5DON/vue-ui-picture-bd-marker#7]
后台返回大量数据，显示不完整，需要x-6,y-12才能显示出来所有的数据，这是什么原因造成的？

**Comment by sunshengfei** [comment]
能详细说明问题吗，谢谢
我自测1000个都是没问题的
![image](https://user-images.githubusercontent.com/8654525/86445327-c5ab8700-bd44-11ea-8ec6-93c788d7c4bf.png)
