### ISSUE TITLE
1.3.6版本关于onAnnoRemoved参数

### ISSUE THREAD

**Issue by wsxxwzh0814** [FRED5DON/vue-ui-picture-bd-marker#8]
在点击标记区域的'x'触发onAnnoRemoved方法时 其参数传递的参数为0，麻烦确认一下。

**Comment by sunshengfei** [comment]
收到

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: wsxxwzh0814 <notifications@github.com>
发送时间: Monday, July 13, 2020 2:20:56 PM
收件人: sunshengfei/vue-ui-picture-bd-marker <vue-ui-picture-bd-marker@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: [sunshengfei/vue-ui-picture-bd-marker] 1.3.6版本关于onAnnoRemoved参数 (#8)


在点击标记区域的'x'触发onAnnoRemoved方法时 其参数传递的参数为0，麻烦确认一下。

―

**Comment by sunshengfei** [comment]
@wsxxwzh0814  发布了 1.3.7

**Comment by wsxxwzh0814** [comment]
收到

**Comment by wsxxwzh0814** [comment]
OK 可以了 谢谢

**Comment by sunshengfei** [comment]
😊
